### ISSUE TITLE
Render bug on Ms and Ws

### ISSUE THREAD

**Issue by ContextSans** [adityab/memecached#2]
Some sort of render bug occurs on Ms and Ws, causing a black spike above and below each point. They're more visible with larger text (fewer characters per line). 
Observed in Firefox 9.01.

**Comment by adityab** [comment]
Not a bug!
This is due to different Canvas implementations in Gecko and Webkit.

Webkit does this much better, see a comparison:
<img src = "http://dl.dropbox.com/u/40496552/ImageBin/memeshot.png" align = "center"></img>

**Comment by ContextSans** [comment]
Should probably mention in the docs that you don't intend to support Firefox then.
